### ISSUE TITLE
Mark given by Fitchfork?

### ISSUE THREAD

**Issue by egeldenhuys** [m3h/cos212-ass5-Tester#1]
Thank you for making your tests public. When I get to the testing stage I will provide further feedback.

@m3h, What mark did Fitchfork give you after passing all the tests in this repo?

**Comment by m3h** [comment]
Fitchfork gave me 97/97, but there's I suspect there are still some errors in the tester.
This morning I edited large.txt  (it was a multigraph, which we don't have to handle), but I think there might be some more stuff...
Basically a friend used it and didn't get quite the same output, but he also got 97/97
